version: '3'

x-base-image:
  &base_image_config
  image: geerlingguy/docker-ubuntu1804-ansible
  privileged: yes
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

services:
  node1:
    << : *base_image_config
    container_name: 192.168.0.11
  node2:
    << : *base_image_config
    container_name: 192.168.0.12
  node3:
    << : *base_image_config
    container_name: 192.168.0.13
  control:
    << : *base_image_config
    container_name: 44.55.66.77